services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    networks:
      - music-net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
    volumes:
      - ${MEDIA_PATH}/jellyfin/config:/config:Z
      - ${MEDIA_PATH}/media:/media:Z
    ports:
      - 8096:8096
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    networks:
      - music-net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - WEBUI_PORT=8080
    volumes:
      - ${MEDIA_PATH}/qbittorrent/config:/config:Z
      - ${MEDIA_PATH}/downloads:/downloads:Z
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    hostname: slskd
    networks:
      - music-net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - ${MEDIA_PATH}/slskd/config:/app/config:Z
      - ${MEDIA_PATH}/downloads:/downloads:Z
    ports:
      - 5030:5030
      - 50300:50300
    restart: unless-stopped

  shelfmark:
    image: ghcr.io/calibrain/shelfmark:latest
    container_name: shelfmark
    hostname: shelfmark
    networks:
      - music-net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
    ports:
      - 8084:8084
    volumes:
      - ${MEDIA_PATH}/shelfmark/config:/config:Z
      - ${MEDIA_PATH}/media/books:/books:Z
    restart: unless-stopped

  forgejo:
    image: codeberg.org/forgejo/forgejo:14
    container_name: forgejo
    hostname: forgejo
    networks:
      - music-net
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ${MEDIA_PATH}/forgejo/data:/data:Z
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx # Fixes the internal DNS lookup for the tunnel
    networks:
      - music-net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${MEDIA_PATH}/nginx/conf:/etc/nginx/conf.d:Z # Critical for Fedora
      - ${MEDIA_PATH}/nginx/certs:/etc/nginx/certs:Z
    restart: unless-stopped

  tunnel:
    container_name: cloudflare-tunnel
    hostname: cloudflare-tunnel
    image: cloudflare/cloudflared:latest
    restart: always
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      - music-net

networks:
  music-net:
    driver: bridge
    name: music-net